### ISSUE TITLE
no Login / Error 302 with 2-way auth via SMS

### ISSUE THREAD

**Issue by altsieben** [vanita5/twittnuker#33]
i use the 2-way authentication on twitter with login code via SMS.
After entering the first password, twittnuker answered with an 302 error. 

![screenshot_2015-01-19-11-19-49](https://cloud.githubusercontent.com/assets/5229707/5799002/9445c68e-9fcd-11e4-8262-50d9be471fcc.png)

there is no chance to enter the SMS credentials.

with regards,
.marc

**Comment by trockenasche** [comment]
Just click on the world icon top right, and you get Twitter login site, where you can use sms credentials.

**Comment by vanita5** [comment]
Twittnuker uses PIN authentication by automatically parsing the the response from Twitter. That's why you just have to enter your username and password.
Two factor authentication can not be parsed because that's not implemented. I might consider to also parse this in the future.

For now you can click on the world icon and login the normal way as @trockenasche recommended :)

**Comment by altsieben** [comment]
Thanks for your hints, i haven't realized the world icon as an option to click. I thought it is just an gimmik symbol to beautify the screen. :)

**Comment by vanita5** [comment]
2FA via SMS or the official Twitter for Android app has been implemented lately
