### ISSUE TITLE
retweet with comment

### ISSUE THREAD

**Issue by JanSchulz** [vanita5/twittnuker#51]
Not sure whats the name, but twitter lets you retweet with a comment, but this doesn't show up properly in the timeline in twittnuker.

If you want a beta tester, I'll be happy to help :-)

**Comment by vanita5** [comment]
They are called quotes ;)

This is implemented in the latest debug build. You can download the apk from here: twittnuker.org/download/twittnuker-debug.apk

Make sure to uninstall Twittnuker first, because this is an unsigned debug build.

I close this issue for now. Please feel free to reopen it if it doesn't work as intended!

Thank you :)
