### ISSUE TITLE
"Media" tab

### ISSUE THREAD

**Issue by Clouddancer** [vanita5/twittnuker#91]
"Media" doesn't show a pic of a photo/video thumbnail when going on the tab. It's just a grey circle and some lines

**Comment by vanita5** [comment]
Right, this is due to Twitter's limitation of the official API.

Workaround for you:
* Remove your account from Twittnuker
* On the login screen open the API settings (server logo in the top of the screen)
* -> Load defaults
* -> Choose *Twitter for Android*
* Go back and login again

This will also give you reetweet/like/follow notifications in the interactions tab ;)

I will make sure the media tab is hidden if the media timeline is not available.
And btw thank you for your bug reports!

**Comment by Clouddancer** [comment]
Thank you!! I followed your instructions and logged in again. The "Media" tab shows now the thumbnails of photos and videos. I will check the other things in the next days. 
You're welcome :) and thank you very much for your help.

**Comment by Clouddancer** [comment]
Okay just checked. The "who retweeted" and "who faved" list works now. Thank you again :)

**Comment by Clouddancer** [comment]
It doesn't work again :(
